name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Install swiftlint
      run: brew install swiftlint
    - name: Lint
      run: swiftlint
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
