name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v2

      - name: Prepare Build
        run: brew reinstall swiftlint

      - name: Build
        run: swift build -v

      - name: Lint
        run: swiftlint

      - name: Run tests
        run: swift test -v --enable-code-coverage
